---
title: "Meteorite Landings"
author: "Bikram Maharjan"
date: "2/18/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE}

library(tidyverse)
library(ggplot2)
library(reshape2)
library(data.table)
library(lubridate)
library(compare)


```

### Prepare the dataset
```{r}

# Read the meteorite-landings.csv downloaded from https://www.kaggle.com/nasa/meteorite-landings
meteorite_landings <- read.csv('meteorite-landings.csv', stringsAsFactors = FALSE)

# Reorder the columns for clarity
mlandings <- meteorite_landings[c(2,1,6,7,5,3,4,8,9,10)]

head(mlandings)
```


```{r}

# Fetch `reclat` and `reclong` column to get Geo Location Name. Eg: Country / Region name
latitude.longitude <- meteorite_landings[c(8,9)]

# Round off the Latitude and Longitude value to 4 digits
# 4th Decimal place: The fourth decimal place is worth up to 11 m: it can identify a parcel of land
# Referring to: 
# https://gis.stackexchange.com/questions/8650/measuring-accuracy-of-latitude-and-longitude
# https://en.wikipedia.org/wiki/Decimal_degrees
latitude.longitude$reclat <- round(latitude.longitude$reclat, digits = 4)
latitude.longitude$reclong <- round(latitude.longitude$reclong, digits = 4)


# Join `reclat` and `reclong` into one column to get distinct coordinates
# The reason to do this is to have unique coordinates that we can re-apply with the full dataset
latitude.longitude$lat_lng <- mapply(
  function(x, y){
    paste(x,y, sep = ",")
  }, 
  latitude.longitude$reclat, 
  latitude.longitude$reclong
  ) 

# Fetch distinct Geo Location & keep all the columns
distinct.latitude.longitude <- latitude.longitude %>% 
                                drop_na() %>%
                                select(reclat, reclong, lat_lng) %>%
                                distinct(lat_lng, .keep_all = TRUE)

 


# Save the file in CSV
# Use Python script to call GeoNames API and get corrosponding Country Names
write.csv(distinct.latitude.longitude, "distinct_latitude_longitude.csv")


```

```{r}

read.csv('distinct_latitude_longitude.csv', stringsAsFactors = FALSE)


```


#### COUNTRY NAME

```{r}

## Read CSV
meteorite_landings <- read.csv('meteorite-landings.csv', stringsAsFactors = FALSE)
country_csv <- read.csv('CSVcountry_name.csv', stringsAsFactors = FALSE)
CSVcountry_name2 <- read.csv('2_CSVcountry_name.csv', stringsAsFactors = FALSE)
CSVcountry_name3 <- read.csv('3_CSVcountry_name.csv', stringsAsFactors = FALSE)
CSVcountry_name4 <- read.csv('4_CSVcountry_name.csv', stringsAsFactors = FALSE)
CSVcountry_name5 <- read.csv('5_CSVcountry_name.csv', stringsAsFactors = FALSE)


CSVcountry_name6 <- read.csv('6_CSVcountry_name.csv', stringsAsFactors = FALSE)


###
country_clean_csv <- country_csv %>% select(country, country_code, latitude, longitude) %>% filter(country != 'Unknown')

###
unknown_country2 <- CSVcountry_name2 %>% select(country, country_code, latitude, longitude) %>% filter(country != 'Unknown')

###
unknown_country3 <- CSVcountry_name3 %>% select(country, country_code, latitude, longitude) %>% filter(country != 'Unknown')

###
unknown_country4 <- CSVcountry_name4 %>% select(country, country_code, latitude, longitude) %>% filter(country != 'Unknown')

###
unknown_country5 <- CSVcountry_name5 %>% select(country, country_code, latitude, longitude) %>% filter(country != 'Unknown')



###
unknown_country6 <- CSVcountry_name6 %>% select(country, country_code, latitude, longitude, distance, location_type )


good55 <- read.csv('good5.csv', stringsAsFactors = FALSE)

good55$distance <- 0
good55$location_type <- "land"
good55$X <- NULL
write.csv(good55, "good55.csv")


```


```{r}



#########################################
# good csv
write.csv(unknown_country6, "good6.csv")

# unknown csv
write.csv(unknown_country5, "unknown_country5.csv")

#########################################


```

```{r}







match_lat_lng <- read.csv('distinct_latitude_longitude.csv', stringsAsFactors = FALSE)



```


```{r}

country_final <- read.csv('country_name_final.csv', stringsAsFactors = FALSE)

country_final %>% select(country) %>% group_by(country) %>% tally(sort = TRUE)


country_final$distance <- 0
country_final$location_type <- "land"

country_final$X <- NULL

write.csv(country_final, "country_name_final_type.csv")


```

```{r}

country_final <- read.csv('country_name_final_type.csv', stringsAsFactors = FALSE)
country_final$X <- NULL

write.csv(country_final, "country_name_final_migrate.csv")


```

# COMPARE - FIND MISMATCH
```{r}

a1 <- data.frame(a = 1:5, b = letters[1:5])
a2 <- data.frame(a = 1:3, b = letters[1:3])
comparison <- compare(a1,a2,allowAll=TRUE)
comparison$tM


```



```{r}


# Group by fall
# Count the number of fall category
# Fell: The meteorite's fall was observed
# Found: The meteroite's fall was not observed, but later found

meteorite.fall <- mlandings %>% group_by(fall) %>% summarise(count = n()) %>% arrange(desc(fall))
meteorite.fall


```



```{r}

# Group by recclass
# This is the class of meteorite
# It is based on physical, chemical, and other characteristics

meteorite.recclass <- mlandings %>% group_by(recclass) %>% summarise(count = n()) %>% arrange(desc(count))

# Displaying top 5 interms of count 
head(meteorite.recclass, 5)
```


```{r}


# Group by geo Geo Location
distinct_geo_location <- mlandings %>% group_by(GeoLocation, reclat, reclong) %>% summarise(count = n()) %>% arrange(desc(count))


# Group by year_fell and count
meteorite_fall_year_count <- mlandings %>% group_by(year_fall) %>% summarise(count = n()) %>% arrange(desc(year_fall)) %>% filter(count > 50 & is.na(year_fall) == FALSE)


mlandings %>% group_by(year_fall) %>% summarise(count = n()) %>% arrange(desc(year_fall))

```




```{r}

# Read country_code.csv
country_code <- read.csv('list_country_code.csv', header=TRUE ,sep="," , stringsAsFactors = FALSE)
country_name <- read.csv('country_name.csv', header=TRUE ,sep="," , stringsAsFactors = FALSE)

country_code
country_name


distinct_geo_location_775 <- head(distinct_geo_location, 775)
```



```{r}
distinct_geo_location_775$country_name <- country_name$country_name

```


```{r}

country_name_count <- distinct_geo_location_775 %>% group_by(country_name) %>% summarise(count = n()) %>% arrange(desc(count)) %>% filter(count > 15) 

country_name_count %>% summarise_all(funs(sum))
sum(country_name_count[, 'count'])

```


```{r}

ggplot(country_name_count, aes(x="", y=count, fill=country_name)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y") +
  theme(axis.text.x=element_blank())+
  scale_fill_brewer(palette="Set1") + 
  ggtitle("More than 50% of the Meteorite falls in the Antartica") +
  labs(fill = "Countries with more than 150 Meteorite fall")+
  theme_void() 


ggplot(country_name_count, aes("", count, fill = country_name)) +
    geom_bar(width = 1, size = 1, color = "white", stat = "identity") +
    coord_polar("y") +
    geom_text(aes(label = paste0(round((count)/693, 2) * 100, "%")), color = "white", size=4,
              position = position_stack(vjust = 0.5)) +
    labs(x = NULL, y = NULL, fill = NULL, 
         title = "More than 50% of the Meteorite fell in the Antartica") +
    guides(fill = guide_legend(reverse = TRUE)) +
    scale_fill_manual(values = c("#650360", "#00759A", "#DC9B32", "#A8B400", "#474334", "#A33F1F", "#6A7F10")) +
    theme_classic() +
    theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank(),
          plot.title = element_text(hjust = -3, color = "#000000"))+
    labs(fill = "Geo Location with more than 150 Meteorite fall")




```



```{r}

# Prepare the plot


# Prepare the plot
ggplot(meteorite_fall_year_count, aes(year_fall, count)) + 
  geom_smooth(stat = "identity") +
  ggtitle("Countried with highest cases after China (As of March 14th 2020)")+
  xlab("Timeseris of ")+ 
  ylab("Total Cases")+
  theme(axis.text.x = element_text(angle = 60, hjust = 1), 
        plot.title = element_text(hjust = 0.5),
        legend.title = element_text("Status of COVID-19"))



```



